# Generated by Django 2.1 on 2018-11-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_sign_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='year_in_school',
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='signup',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
