# Generated by Django 2.1 on 2018-11-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_sign_app', '0002_auto_20181123_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='re_email',
        ),
        migrations.AddField(
            model_name='signup',
            name='re_password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
